ext {
    extName = 'ProComic'
    extClass = '.ProComic'
    extVersionCode = 1
    isNsfw = false
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlinx-serialization'

android {
    compileSdk 34
    namespace "eu.kanade.tachiyomi.extension.ar.procomic"

    defaultConfig {
        minSdk 21
        targetSdk 34
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = '11'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation project(':lib:cookieinterceptor')
    implementation libs.bundles.common
    compileOnly libs.tachiyomi.lib
}
